### PR TITLE
feat: detect and fix err.String() calls

### PR DESCRIPTION
**Pull request by dnwe**
Adds support for detecting and fixing the following Errorf case where the developer had previously add a call to `.Error()` in their Errorf statement:
```diff
-fmt.Errorf("failed for %s with error: %s", "foo", err.Error())
+fmt.Errorf("failed for %s with error: %w", "foo", err)
```

This PR also switches to running the tests with the new [analysistest.RunWithSuggestedFixes](https://godoc.org/golang.org/x/tools/go/analysis/analysistest#RunWithSuggestedFixes) helper to verify the `-fix` behaviour using golden files.

### CODE REVIEW

**Comment by dnwe** [comment]
@fatih I fully understand if you're busy at the moment, but as I wasn't sure if you'd seen the PR or not, I thought I'd @ you to see if you'd be free to do a review of the changes

**Comment by fatih** [comment]
I like this change. Also, thanks for introducing `analysistest.RunWithSuggestedFixes`. Sorry for the late response. I moved from another continent with the whole family and just started having some time for myself.

**Comment by fatih** [comment]
This feature is now included in `v1.3.1`: https://github.com/fatih/errwrap/releases/tag/v1.3.1

**Comment by dnwe** [comment]
@fatih thanks!

**Pull request merged**
